# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("https://montreal.lufa.com/en/employee/view/id/417207")
    self.driver.set_window_size(1440, 875)
    self.driver.find_element(By.CSS_SELECTOR, ".half:nth-child(10) > .twothird").click()
    self.driver.find_element(By.CSS_SELECTOR, ".half:nth-child(10) > .twothird").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".half:nth-child(10) > .twothird")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".half:nth-child(10) > .twothird").click()
    self.driver.find_element(By.CSS_SELECTOR, ".half:nth-child(10) > .twothird").click()
    self.driver.find_element(By.CSS_SELECTOR, ".half:nth-child(10) > .twothird").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".half:nth-child(10) > .twothird")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".half:nth-child(10) > .twothird").click()
    self.driver.find_element(By.CSS_SELECTOR, ".half:nth-child(10) label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".half:nth-child(10) label").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".half:nth-child(10) label")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".half:nth-child(10) label").click()
    self.driver.close()
  
